#!/usr/bin/dh-exec

debian/initramfs/dropbear-conf => etc/initramfs-tools/conf-hooks.d/dropbear
debian/initramfs/dropbear-hook => usr/share/initramfs-tools/hooks/dropbear

debian/initramfs/premount-dropbear => usr/share/initramfs-tools/scripts/init-premount/dropbear
debian/initramfs/bottom-dropbear => usr/share/initramfs-tools/scripts/init-bottom/dropbear
debian/initramfs/bottom-ifdown => usr/share/initramfs-tools/scripts/local-bottom/ifdown
